### ISSUE TITLE
编程经验基本0，请教课程该如何学习

### ISSUE THREAD

**Issue by Qualiazero** [jackfrued/Python-100-Days#323]
如题，我是一名非计算机专业的入门学习者，请问该课程该如何学习？我搜寻了很多最后用VS Code打开了github fork过来的代码，预览.md文档，但是总觉得这么做似乎不是正确学习的方式，一个个点开文件夹看.md文档似乎也不对，请问正确的方式是什么？

**Comment by sariusli** [comment]
我也是个非计算机专业者，学这个就纯属兴趣。
我也在网上问过很多这样的问题，他们都说多练。我想，看md文档，然后学习它的写法，掌握基本语法与框架，再有就是多看别人的代码，因为阶的我也没学，所以帮不到你，对不起啦😊。最后就是老生常谈的，坚持！
---原始邮件---
发件人:"Qualiazero"<notifications@github.com>
发送时间:2019年10月5日 星期六 上午9:10
收件人:"jackfrued/Python-100-Days"<Python-100-Days@noreply.github.com>
抄送:"Subscribed"<subscribed@noreply.github.com>
主题:[jackfrued/Python-100-Days] 编程经验基本0，请教课程该如何学习 (#323)

如题，我是一名非计算机专业的入门学习者，请问该课程该如何学习？我搜寻了很多最后用VS Code打开了github fork过来的代码，预览.md文档，但是总觉得这么做似乎不是正确学习的方式，一个个点开文&#x4EF6;夹看.md文档似乎也不对，请问正确的方式是什么？

&mdash;

**Comment by Qualiazero** [comment]
> 我也是个非计算机专业者，学这个就纯属兴趣。 我也在网上问过很多这样的问题，他们都说多练。我想，看md文档，然后学习它的写法，掌握基本语法与框架，再有就是多看别人的代码，因为阶的我也没学，所以帮不到你，对不起啦blush。最后就是老生常谈的，坚持！ ---原始邮件--- 发件人:"Qualiazero"<notifications@github.com> 发送时间:2019年10月5日 星期六 上午9:10 收件人:"jackfrued/Python-100-Days"<Python-100-Days@noreply.github.com> 抄送:"Subscribed"<subscribed@noreply.github.com> 主题:[jackfrued/Python-100-Days] 编程经验基本0，请教课程该如何学习 (#323) 如题，我是一名非计算机专业的入门学习者，请问该课程该如何学习？我搜寻了很多最后用VS Code打开了github fork过来的代码，预览.md文档，但是总觉得这么做似乎不是正确学习的方式，一个个点开文&#x4EF6;夹看.md文档似乎也不对，请问正确的方式是什么？ &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly,view it on GitHub, ormute the thread.


感谢您的回答，但是您在说啥？
我是想请教应该用什么软件或者工具打开这个教程并读取，具体的软件，或者其他手段，恕我无法看懂您的意思。

**Comment by Qualiazero** [comment]
继续求帮助

**Comment by Dreamone1** [comment]
> 继续求帮助

请你好好看看最开头的文档，写的很详细，需要下载什么都有写！

**Comment by ic3evi1** [comment]
还是找一套比较系统的视频跟着学习，然后看文档，敲敲代码，这样入门轻松点。

**Comment by nominz** [comment]
建议跟着视频教程学




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"冰神舞"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月5日(星期二) 下午4:01
收件人:&nbsp;"jackfrued/Python-100-Days"<Python-100-Days@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [jackfrued/Python-100-Days] 编程经验基本0，请教课程该如何学习 (#323)




还是找一套比较系统的视频跟着学习，然后看文档，敲敲代码，这样入门轻松点。

**Comment by herowaste** [comment]
可以用VScode加上markdown插件

**Comment by herowaste** [comment]
没有什么正确方式吧，我也是非计算机专业，一般就是网页看markdown文件，另外vscode跟着教程和例题打代码就行了

**Comment by nominz** [comment]
4
         
软件安装 - VSCode
     
        
5
         
安装补丁 - 0201-VSCode右键菜单补丁
     
        
6
         
插件安装 - AnacondaExtensionPack
     
        
7
         
插件安装 - Chinese(Simplified)Language…
     
        
8
         
插件安装 - CodeRunner
     
        
9
         
插件安装 - filesize
     
        
10
         
插件安装 - Guides
     
        
11
         
插件安装 -   koroFileHeader
     
        
12
         
插件设置 - 公司代码头部注释设置
     
        
13
         
插件安装 - Material   Theme
     
        
14
         
插件设置 - 配色主题为Material Theme
     
        
15
         
插件安装 - openinbrowser
     
        
16
         
插件安装 - Prettier -   Code formatter
     
        
17
         
插件安装 - Python
     
        
18
         
插件安装 - Vetur
     
        
19
         
插件安装 - vscode-icons
     
        
20
         
插件设置 - 图标主题设置为vscode-icons
     
        
21
         
插件安装 - Vue 2 Snippets
     
        
22
         
插件安装 - tabout
     
 




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"herowaste"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月5日(星期二) 下午4:12
收件人:&nbsp;"jackfrued/Python-100-Days"<Python-100-Days@noreply.github.com&gt;;
抄送:&nbsp;"徐辉"<nominz@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [jackfrued/Python-100-Days] 编程经验基本0，请教课程该如何学习 (#323)




可以用VScode加上markdown插件

**Comment by nominz** [comment]
你是学生吗？我的微信号13920410073，用电子邮件聊天怪怪的还是加微信吧
学编程还是有正确的方式的，你这样瞎看太耽误时间，而且入门的学习曲线太陡峭
学习编程需要用一步一步小的胜利来不断激励自己




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"herowaste"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月5日(星期二) 下午4:14
收件人:&nbsp;"jackfrued/Python-100-Days"<Python-100-Days@noreply.github.com&gt;;
抄送:&nbsp;"徐辉"<nominz@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [jackfrued/Python-100-Days] 编程经验基本0，请教课程该如何学习 (#323)




没有什么正确方式吧，我也是非计算机专业，一般就是网页看markdown文件，另外vscode跟着教程和例题打代码就行了

**Comment by LlliYang** [comment]
我学过编程啊~

________________________________
发件人: nominz <notifications@github.com>
发送时间: Tuesday, November 5, 2019 4:22:45 PM
收件人: jackfrued/Python-100-Days <Python-100-Days@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [jackfrued/Python-100-Days] 编程经验基本0，请教课程该如何学习 (#323)

你是学生吗？我的微信号13920410073，用电子邮件聊天怪怪的还是加微信吧
学编程还是有正确的方式的，你这样瞎看太耽误时间，而且入门的学习曲线太陡峭
学习编程需要用一步一步小的胜利来不断激励自己




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"herowaste"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月5日(星期二) 下午4:14
收件人:&nbsp;"jackfrued/Python-100-Days"<Python-100-Days@noreply.github.com&gt;;
抄送:&nbsp;"徐辉"<nominz@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [jackfrued/Python-100-Days] 编程经验基本0，请教课程该如何学习 (#323)




没有什么正确方式吧，我也是非计算机专业，一般就是网页看markdown文件，另外vscode跟着教程和例题打代码就行了

―
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.

―

**Comment by raunbobo** [comment]
能不能不要抄送订阅的人...

在 2019年11月5日，17:59，LlliYang <notifications@github.com> 写道：

﻿我学过编程啊~

________________________________
发件人: nominz <notifications@github.com>
发送时间: Tuesday, November 5, 2019 4:22:45 PM
收件人: jackfrued/Python-100-Days <Python-100-Days@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [jackfrued/Python-100-Days] 编程经验基本0，请教课程该如何学习 (#323)

你是学生吗？我的微信号13920410073，用电子邮件聊天怪怪的还是加微信吧
学编程还是有正确的方式的，你这样瞎看太耽误时间，而且入门的学习曲线太陡峭
学习编程需要用一步一步小的胜利来不断激励自己




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"herowaste"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月5日(星期二) 下午4:14
收件人:&nbsp;"jackfrued/Python-100-Days"<Python-100-Days@noreply.github.com&gt;;
抄送:&nbsp;"徐辉"<nominz@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [jackfrued/Python-100-Days] 编程经验基本0，请教课程该如何学习 (#323)




没有什么正确方式吧，我也是非计算机专业，一般就是网页看markdown文件，另外vscode跟着教程和例题打代码就行了

―
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.

―

**Comment by Qualiazero** [comment]
> 
> 
> 没有什么正确方式吧，我也是非计算机专业，一般就是网页看markdown文件，另外vscode跟着教程和例题打代码就行了

感谢建议

**Comment by Qualiazero** [comment]
> 
> 建议跟着视频教程学
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"冰神舞"<notifications@github.com&gt;; 发送时间:&nbsp;2019年11月5日(星期二) 下午4:01 收件人:&nbsp;"jackfrued/Python-100-Days"<Python-100-Days@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [jackfrued/Python-100-Days] 编程经验基本0，请教课程该如何学习 (#323) 还是找一套比较系统的视频跟着学习，然后看文档，敲敲代码，这样入门轻松点。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

比如？求几个推荐的？

**Comment by nominz** [comment]
强力Django+杀手级Xadmin打造在线教育平台
Python前后端分离开发Vue + Django REST Framework 实战电商项目


募课网原版，大约几百元，不过淘宝有售，价格嘛，大约几百日元。。。。。逃




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Qualiazero"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月11日(星期一) 凌晨0:52
收件人:&nbsp;"jackfrued/Python-100-Days"<Python-100-Days@noreply.github.com&gt;;
抄送:&nbsp;"徐辉"<nominz@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [jackfrued/Python-100-Days] 编程经验基本0，请教课程该如何学习 (#323)



 
建议跟着视频教程学
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"冰神舞"<notifications@github.com&gt;; 发送时间:&nbsp;2019年11月5日(星期二) 下午4:01 收件人:&nbsp;"jackfrued/Python-100-Days"<Python-100-Days@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [jackfrued/Python-100-Days] 编程经验基本0，请教课程该如何学习 (#323) 还是找一套比较系统的视频跟着学习，然后看文档，敲敲代码，这样入门轻松点。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
比如？求几个推荐的？

**Comment by ic3evi1** [comment]
> > 建议跟着视频教程学
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "冰神舞"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2019年11月5日(星期二) 下午4:01 收件人: "jackfrued/Python-100-Days"<[Python-100-Days@noreply.github.com](mailto:Python-100-Days@noreply.github.com)>; 抄送: "Subscribed"<[subscribed@noreply.github.com](mailto:subscribed@noreply.github.com)>; 主题: Re: [jackfrued/Python-100-Days] 编程经验基本0，请教课程该如何学习 (#323) 还是找一套比较系统的视频跟着学习，然后看文档，敲敲代码，这样入门轻松点。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 比如？求几个推荐的？

可以到淘宝上买9.9元的那种，这个方法我一般人不告诉你。😂😂😂

**Comment by jndxhuxiehang** [comment]
这种情况其实我建议跟廖雪峰老师的教程而不是本教程，本教程目前我个人感觉不适合完全的新手

**Comment by wasd00wdsa** [comment]
去mooc看一些老师讲的视频，讲的很详细，听完再来看这个很好懂

**Comment by pieces-0** [comment]
我也这么觉得，好难，特别是数学。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jndxhuxiehang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 晚上9:08
收件人:&nbsp;"jackfrued/Python-100-Days"<Python-100-Days@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [jackfrued/Python-100-Days] 编程经验基本0，请教课程该如何学习 (#323)




这种情况其实我建议跟廖雪峰老师的教程而不是本教程，本教程目前我个人感觉不适合完全的新手

**Comment by jeffforfun** [comment]
只是python的话。把菜鸟的基础语法先掌握了，然后简单问题开始模仿写。
多看多写，打基础。我是推荐新手学C，从数据结构开始学。

**Comment by jin006s** [comment]
本教程讲的内容不够详细 初学者建议看廖雪峰老师的教程
