### ISSUE TITLE
Day 9 的笔记和在github上的列出的内容不太相符

### ISSUE THREAD

**Issue by InstantWindy** [jackfrued/Python-100-Days#48]
Day9的笔记内容部分缺少

**Comment by jackfrued** [comment]
Of course you can

**Comment by jackfrued** [comment]
Of course, you can.

**Comment by chenruhai** [comment]
什么时候更新 数据挖掘和机器学习呀！


 
---原始邮件---
发件人: "DEEPIKA KAMLESH TIWARI"<notifications@github.com>
发送时间: 2019年5月6日(星期一) 晚上11:05
收件人: "jackfrued/Python-100-Days"<Python-100-Days@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [jackfrued/Python-100-Days] Day 9 的笔记和在github上的列出的内容不太相符 (#48)



can i also get notes so that i can also contribute?
